services:
  funpay-cardinal:
    build: .
    container_name: funpay-cardinal
    restart: unless-stopped
    env_file: .env
    volumes:
      - ../files/configs:/usr/src/app/configs
      - ../files/logs:/usr/src/app/logs
      - ../files/storage:/usr/src/app/storage
      - ../files/plugins:/usr/src/app/plugins
